language: node_js
node_js:
  - "0.12"
compiler: gcc
before_install:
- mkdir -p $GOPATH/src/github.com/lucibus
- mv $PWD $GOPATH/src/github.com/lucibus/lucibus
- cd $GOPATH/src/github.com/lucibus/lucibus
- export PATH=$PATH:$GOPATH/bin
- eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.5 bash)"
- go version
- gimme version
install:
- cd $TESTFOLDER
- make travis_install
script:
- make travis_script
after_success:
- make travis_after_success
before_deploy:
- make bindata_assetfs.go
- go get github.com/mitchellh/gox
- mkdir -p dist
- gox -osarch="linux/386 linux/amd64 linux/arm windows/386 windows/amd64" -output="dist/lucibus-{{.OS}}-{{.Arch}}"
- make bintray.json
- cat bintray.json
deploy:
- provider: releases
  api_key:
    secure: wg+fDCdRBr+2PJUoTCi98kqzYG55HtT0njm6+dTQylmo4S/teyFsLi5RgtkQYQy5ZdUobB1k0Ydze1cYYpW3UgGTI7x07AlAW1h7f6CBpDj/VqZ7O+AGEmpGArTpK/970sY0S591O3d8NlU8x555KLvH0IgxdOVtzGFRvcFZj1ZL63bqXWw2bSx0NwVzjC5e5r2DhQln+9jHvxJBMEE9UyuhpWZDllEnTm9wFUANmRbzD16KjzrTPeBUojdyn2pYq5/sp2ArwigSpcjCPs3ZJLKEG6h0m0OBHnDPn1QRsQz5hymOy+4e4uHKPXm+LveCAX5rGy97q4DqimylS+mDOpzKjgcYRJUEJJBfDQCenp0i0R78ffSFnKD2mWC42j0c0mMxa2FOcR/7U82lg4Go7RRtSantiln46Iah4mnVs06zb+LXOc6bDNq7g/76jFAXqLlrkzzwZmej8RNMVLt9CGWiZW9L3qrr3ogK3ENqaSz9teyye7z0W6+l5GxvQ/cZzCoom1Pqt3XuK+JrGVi0991RxqEXAOvMR7U7UQG9Lcx3bnbL1O7D8vdp8mpTLR6XQqZAoNCIbHJrd5AhHk8EjEt6czoZ0B6lE6gLzhydWCPdPzAueDjnrh20x/LWQeJwUrZIpYwBQ8kLXv8rUXUpfZz4J7mEyWU9S/RxC8xD29s=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  condition: $TESTFOLDER = .
  on:
    tags: true
    condition: $TESTFOLDER = .
- provider: bintray
  key:
    secure: TPVDI+5speVYv2zqhjhjwBES3d1RFPvBJzUvdMqbBwUl/cdP0/X2I93rxNso6G6JguEPkKIkdZfc+F2fKutsW1xt33fN61KfVi1fLaBTW+pjF8vshb53GMmuOdyfDrpcFHSEC9DjhXVP6TEqrshFwlxF4byGKBZGwbuuI4lzjXGIld7HxCf+UC7zngiOpdijcN0s3U/N2RAM7tg4FEwOZWQFvOd9DvFs4sfbayWZZZu3WB6xbTG4Hk3DWpPcu4+aPaoh2EKWm3QlmvXHRnrwaOp4Ug4gkaXYppOq3WnO4uUfKGqzzs8s/vJfTtvQAtvv4QPsiGIa6EmiqqHY9cuHahlQJc49XD9tBgxFin0xfXqg2rsluMq6aqzkrAYv2vIlNJU6QjqE7paCeyKXla7wtxS1BlzDJQiFH6vfezAn97olMkpOym1dyr+r0xG8dW4x3f997WEMzXVvNwimK/R9qLEPJv9yAjAegghPiOdlpmHin6K4Iafo+wnm6vNgJwHzBYWWTfT8oLeSu7xcaCb+bdEO89AS5oHVCT260F3cxaWWYwQ28NBaZqH1rCuBiJSBDx0b4VnK4Hd0y28Yi27cnG6qFJOHU/iw4zP+ANuXykYn41f3ba7zs7nPNLkGopLGjqSeCeoiTB3QY3fBxtNw1CS0Ek5xBYx7JZtcBYogxmc=
  on:
    condition: $TESTFOLDER = .
  file: bintray.json
  user: saulshanabrook
notifications:
  slack:
    secure: 08MZEuOb0verBf76HRBCuv+5JQErr02ElNn7y5vWnuT7vMjnB8KkXz5RwyF0kz/QdqznsF32C9Tb3kQdXvwoWgdUpx5xCSJZohqB9lbElmLAZkghbG7Il0ciOOoXerq6/Zlz9iTY/i9o8lCIGijnP4PlSL1JF9lLCejslzWkjo/g75eHJGZ6ISeJbNC+0IdOlWhJKLTRxF59tWfzsblwuHpfcAZFVadSq4dwD0w94ZEjmvPUR1zJuqKd62mMSTj1toHcvYsDeSWvE5mkvKJpgKcm7lN3nemrEcqb3C2HRM1zimLzDblcyZH+9CHPUukMYFJewTO6gNxa3aXNl223ltBoY/99bDZmL3leT2syAEWZ5QhA3w+gDu6HCr6tZCR2Tbs/Xd3mEAsksQ+uBIMLGkyvJkVzEzhbyJ89s3fdz9NXedMEM77FE3oOv2jN+8f9NAj4GgleWoGW1vpc39r7CMRQ77n4bV1tdPeyCemsgsDW5ABUZrMa2RHT/W//1QLZCFLdeQUyKwOqDgQYJgAA/YJsz4lBfhbhp9roYZUI50IlnzHr2A/6lZMybl5wqpp+iAOimRmizJjJi1Jz6heLAud3e5AQsyE9dGE4CMUK0DzIKdMydwwlp+L0s1fh8msKVKXchMs+PLOxmqXIfUlscRQCw5tyUFkIlaK2nhVZYCI=
  email: false
env:
  matrix:
  - TESTFOLDER=subicul
  - TESTFOLDER=caido
  - TESTFOLDER=.
  global:
  - GOPATH=~/gopath/
  - GO15VENDOREXPERIMENT=1
  - secure: 1FmlXg7by7kwg8SIXRy3iSAUPVZXxmU4Keub0rzAh5CA6K3YLCURyucSm/I67RF2TWGxpPIo6UNUX+PrSkqWE3IfPYQGgNqkj/R/QHIDPfwtrmuMvtbabqi8lRxXJHSuS6Bz9TkX5ZkmH8BHVSfvOtyI4Y1Am726Bd+Dd/QxWbXN7Gt3HBVP1Ty6Z5Sb5rDYh50xDK9RAQEg6/v2DIcaPttOTmtlkJdIUArYZN9C6XSh23Au4NTwn4TkXXjwWShmSuK28mDq9UpJJqRdanYmP5E8PqFhzMEAy5PmpXSPV5Ag6kxOOLu4zOpnA1z3IWADJJwwJM3iXIrLGCB9VTQVeQFxE9XWBcMzYUApdH6+S5LmiUmCLCARGcG9tV4qJlViipGF8Aj5PNNCpf8B5K0wymZCdst21iVrDdWEWmFh/I6Dmhz2mn1LMzKBfrFbyYWHl1Jy7ucYQEPau4bU29zw1r9UJmqMBIyXuEYnnpXaLVUYLNpq7N03imELK5G+8tXMlxASeyAYYiZ+tt4EDIsqoBnaAZm2Rb+PRlRv7nPm+TJ2QAgKzCxgGvLrFyzAMRzXZVnQNebZQpUJRbDBsRRlVQcAETIrt5aclSq1gpsWetwxXI1Lj50tapxEo6z1KHp/92Jk7lzVIHme4nejfKoTKPIncc5taVDewT0FSEwpUeM=
  - secure: 5mdnyuS6s1PJorbeoPONd8Ui94456xvScVFPsWga1ihiy1LHJQCQenDZ9+Er++HWBL6V+yN6Qru6ago5txAqb9BxJNBn6+KHhkpnnNK5P++ZHSf6TE9Hwz44o1FkkyKJRNCQEq2b9nsxe+WUdnxPdJs2V4hu833XAvacruCcrBU5Cr6tbyKxVy5JLJA6VmIHeoLkFj8JCQHGKhWYUXYGr0lTENNIS9LSf/BUmmieiy3WNB3gtfeOYQyTzcS9GvZth0Kzyy1l0IwQhWT8A3pd80hN9eVBscGNthaS5u/MOr2BsGP7duYOUeMA7h9csldfkn+4c3dkXpsgfD4hvAVZ9gZAkVxO6Jt7ny4QF6mrgsAXxHo8gDCrHjp1LQo6dv2pjfZ3IWZPE1zElP/BEZOwPqaA05nfRD1/rmUcuaSrzHBTXQMZo1R5PBD2IKSNyyAt+gtpo93HogZ9KXjeOZ8UEdFMQfOME7hzNQXYBCI5/3V12l8vPyHVGQaWCtRLCMKc/0trdLR7YNsLvl5vyfgGl70Ll80yhb+akcxMLX4+/BpeAIGE/sBhnNgyEia6MvTnGMWV1IU6xdMgI93XO/MTJk9I7hUUjmycmt59BRiqMb0yxDOt7RgtOeoHmnf7USwd02+vXpqDHpiAAcMArBoLAuOtQPae3xR/E1EjL80zIzk=
addons:
  sauce_connect: true
